default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: events_gateway_api_devel


test:
  <<: *default
  database: events_gateway_api_test

production:
  <<: *default
  database: events_gateway_api_prod
  username: events_gateway_api
  password: <%= ENV["EVENTS_GATEWAY_API_DATABASE_PASSWORD"] %>
